# Generated by Django 5.2.18 on 2026-10-07 08:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, help_text='Leave blank for the default rate', max_length=60, unique=True)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=8)),
                ('per_kg_charge', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=8)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Free shipping above (subtotal)')),
                ('eta', models.CharField(default='4–7 business days', max_length=50, verbose_name='Delivery estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Online (UPI / Card / Netbanking)'), ('bank', 'Bank transfer (NEFT/RTGS)')], max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=60)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=60)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ship_name', models.CharField(max_length=100)),
                ('ship_phone', models.CharField(max_length=20)),
                ('ship_line1', models.CharField(max_length=200)),
                ('ship_line2', models.CharField(blank=True, max_length=200)),
                ('ship_city', models.CharField(max_length=80)),
                ('ship_state', models.CharField(max_length=60)),
                ('ship_pincode', models.CharField(max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Items total (incl. GST)')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery (incl. GST)')),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('courier', models.CharField(blank=True, max_length=60)),
                ('tracking_number', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=40)),
                ('hsn_code', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
    ]
